# Week 6: Hyperparameter Tuning & Model Optimization
Final-Year B.Tech IT Project | AI-Based Resume Screening System

In [1]:
import os
import sys
import pandas as pd

tuning_path = '../models/tuning_results.csv'
if os.path.exists(tuning_path):
    tuning_df = pd.read_csv(tuning_path)
    print('=== TUNING RESULTS ===')
    display(tuning_df)
else:
    sys.path.append(os.path.join('..', 'src'))
    from model_tuner import tune_models
    tuning_df, _, best_name = tune_models('../data', '../models')
    print('Best Model:', best_name)
    display(tuning_df)

=== TUNING RESULTS ===

,Model,Best Parameters,Tuned CV F1,Test Accuracy,Test F1,Test Precision,Test Recall,Test ROC-AUC
0,Logistic Regression,"{'C': 5.0, 'class_weight': 'balanced', 'solver...",0.8026,0.840,0.8222,0.8132,0.8315,0.9175
1,Random Forest,"{'class_weight': 'balanced', 'max_depth': 20, ...",0.8433,0.875,0.8521,0.9000,0.8090,0.9537
2,Support Vector Machine,"{'C': 10.0, 'class_weight': 'balanced', 'kerne...",0.8707,0.895,0.8827,0.8778,0.8876,0.9615

### Tuning Results Analysis
Comparing default baseline vs tuned parameters.

In [2]:
print('Best Model Hyperparameters and Performance:')
display(tuning_df.sort_values(by='Test F1', ascending=False))

Best Model Hyperparameters and Performance:

,Model,Best Parameters,Tuned CV F1,Test Accuracy,Test F1,Test Precision,Test Recall,Test ROC-AUC
2,Support Vector Machine,"{'C': 10.0, 'class_weight': 'balanced', 'kerne...",0.8707,0.895,0.8827,0.8778,0.8876,0.9615
1,Random Forest,"{'class_weight': 'balanced', 'max_depth': 20, ...",0.8433,0.875,0.8521,0.9000,0.8090,0.9537
0,Logistic Regression,"{'C': 5.0, 'class_weight': 'balanced', 'solver...",0.8026,0.840,0.8222,0.8132,0.8315,0.9175